gui:
  theme:
  activeBorderColor:
    - '#b2caed'
    - bold
  inactiveBorderColor:
    - '#96b4aa'
  optionsTextColor:
    - '#b2caed'
  selectedLineBgColor:
    - '#343e43'
  cherryPickedCommitBgColor:
    - '#333b42'
  cherryPickedCommitFgColor:
    - '#b2caed'
  unstagedChangesColor:
    - '#f57f82'
  defaultFgColor:
    - '#f8f9e8'
  searchingActiveBorderColor:
    - '#f5d098'

authorColors:
  '*': '#96b4aa'